#!/bin/bash

#SBATCH -J mixed_train_mask2_r50
#SBATCH -p gpu
#SBATCH -o mixed_standard_mask2_r50_%j.txt
#SBATCH -e mixed_error_mask2_r50_%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=pwagle@iu.edu
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=4
#SBATCH --gpus-per-node 4
#SBATCH --time=20:00:00
#SBATCH -A r00338

#Load any modules that your program needs
module load python/gpu

#Run your program
python tools/train.py configs/mask2former/mask2former_r50_8xb2-160k_mixed-512x512.py
