#!/bin/bash

#SBATCH -J rugd_all_train
#SBATCH -p gpu
#SBATCH -o rugd_all_standard_%j.txt
#SBATCH -e rugd_all_error_%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=pwagle@iu.edu
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=4
#SBATCH --gpus-per-node 4
#SBATCH --time=10:00:00
#SBATCH -A r00338

#Load any modules that your program needs
module load python/gpu

#Run your program
python tools/train.py configs/pspnet/pspnet_r50-d8_4xb4-40k_rugd_all-512x512.py
