#!/bin/bash

#SBATCH -J forestsim_train_segformer_mit-b5
#SBATCH -p gpu
#SBATCH -o forestsim_standard_segformer_mit-b5_%j.txt
#SBATCH -e forestsim_error_segformer_mit-b5_%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=pwagle@iu.edu
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=4
#SBATCH --gpus-per-node 4
#SBATCH --time=20:00:00
#SBATCH -A r00338

#Load any modules that your program needs
module load python/gpu

#Run your program
python tools/train.py configs/segformer/segformer_mit-b5_8xb2-160k_forestsim_all-512x512.py
